[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'othree/yajs.vim'
